spring:
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: 192.168.10.38:9092
          zkNodes: 192.168.10.38:2181

management:
  endpoints:
    web:
      exposure:
        include: "*"