spring:
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181

management:
  endpoints:
    web:
      exposure:
        include: "*"