spring:
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: 192.168.10.38:29092,192.168.10.38:39092,192.168.10.38:49092
          zkNodes: 192.168.10.38:22181

management:
  endpoints:
    web:
      exposure:
        include: "*"