spring:
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: https://e204c23c.ngrok.io/
          zkNodes: https://c984f5c2.ngrok.io/

management:
  endpoints:
    web:
      exposure:
        include: "*"