server.port: 8000

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092,localhost:39092,localhost:49092
          zkNodes: localhost:22181

message: webhooked, bro!

management:
  endpoints:
    web:
      exposure:
        include: "*"